/** ICAO airline designators (the 3-letter callsign prefix) for the carriers most often seen in the sky. */
const AIRLINES: Record<string, string> = {
  // North America
  AAL: "American Airlines",
  DAL: "Delta Air Lines",
  UAL: "United Airlines",
  SWA: "Southwest Airlines",
  ASA: "Alaska Airlines",
  JBU: "JetBlue",
  FFT: "Frontier Airlines",
  NKS: "Spirit Airlines",
  AAY: "Allegiant Air",
  SCX: "Sun Country",
  HAL: "Hawaiian Airlines",
  MXY: "Breeze Airways",
  SKW: "SkyWest Airlines",
  ENY: "Envoy Air",
  RPA: "Republic Airways",
  JIA: "PSA Airlines",
  EDV: "Endeavor Air",
  QXE: "Horizon Air",
  GJS: "GoJet Airlines",
  ASH: "Mesa Airlines",
  UCA: "CommuteAir",
  ACA: "Air Canada",
  ROU: "Air Canada Rouge",
  JZA: "Air Canada Jazz",
  WJA: "WestJet",
  AMX: "Aeroméxico",
  VOI: "Volaris",
  FDX: "FedEx",
  UPS: "UPS Airlines",
  GTI: "Atlas Air",
  EJA: "NetJets",
  LXJ: "Flexjet",
  // Latin America
  AZU: "Azul",
  GLO: "Gol",
  TAM: "LATAM Brasil",
  LAN: "LATAM Airlines",
  AVA: "Avianca",
  CMP: "Copa Airlines",
  // Europe
  RYR: "Ryanair",
  EZY: "easyJet",
  EJU: "easyJet Europe",
  WZZ: "Wizz Air",
  DLH: "Lufthansa",
  BAW: "British Airways",
  AFR: "Air France",
  KLM: "KLM",
  IBE: "Iberia",
  VLG: "Vueling",
  SAS: "SAS",
  FIN: "Finnair",
  AUA: "Austrian Airlines",
  SWR: "Swiss",
  EWG: "Eurowings",
  TAP: "TAP Air Portugal",
  AEE: "Aegean Airlines",
  LOT: "LOT Polish Airlines",
  ITY: "ITA Airways",
  EIN: "Aer Lingus",
  VIR: "Virgin Atlantic",
  BEL: "Brussels Airlines",
  ICE: "Icelandair",
  NOZ: "Norwegian",
  NSZ: "Norwegian",
  TVF: "Transavia France",
  TRA: "Transavia",
  CFG: "Condor",
  TOM: "TUI Airways",
  CLX: "Cargolux",
  THY: "Turkish Airlines",
  PGT: "Pegasus Airlines",
  AFL: "Aeroflot",
  SBI: "S7 Airlines",
  // Middle East & Africa
  UAE: "Emirates",
  QTR: "Qatar Airways",
  ETD: "Etihad Airways",
  SVA: "Saudia",
  ETH: "Ethiopian Airlines",
  MSR: "EgyptAir",
  RAM: "Royal Air Maroc",
  KQA: "Kenya Airways",
  SAA: "South African Airways",
  // Asia-Pacific
  CCA: "Air China",
  CES: "China Eastern",
  CSN: "China Southern",
  CHH: "Hainan Airlines",
  CSZ: "Shenzhen Airlines",
  CXA: "Xiamen Airlines",
  CSC: "Sichuan Airlines",
  CPA: "Cathay Pacific",
  SIA: "Singapore Airlines",
  ANA: "All Nippon Airways",
  JAL: "Japan Airlines",
  KAL: "Korean Air",
  AAR: "Asiana Airlines",
  IGO: "IndiGo",
  AIC: "Air India",
  THA: "Thai Airways",
  VJC: "VietJet Air",
  HVN: "Vietnam Airlines",
  GIA: "Garuda Indonesia",
  MAS: "Malaysia Airlines",
  AXM: "AirAsia",
  CEB: "Cebu Pacific",
  PAL: "Philippine Airlines",
  QFA: "Qantas",
  VOZ: "Virgin Australia",
  ANZ: "Air New Zealand",
};

export function airlineName(code: string): string {
  return AIRLINES[code] ?? code;
}
